### ISSUE TITLE
[QUESTION] 请问为什么去除了表情插件

### ISSUE THREAD

**Issue by J-Yaleen** [ShenQingchuan/HeteroDoc#5]
我在DEMO上看到支持表情插件，但是代码里好像去除了，请问是为什么？

**Comment by ShenQingchuan** [comment]
原因是之前预设的 use case 太简单了，只简单测了测。
但后来我给到更复杂的用例时就遇到了很多问题。

我会先在 DEMO 上移除那个功能。
